In [27]:
import pandas as pd
df = pd.read_csv('./CO2 Emissions_Canada.csv')      #데이터 파일 불러오기
df = df.drop(columns = ['Fuel Consumption Comb (mpg)']) #필요없는 컬럼 제거
df

,Make,Vehicle Class,Engine Size(L),Cylinders,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),CO2 Emissions(g/km)
0,AUDI,COMPACT,2.0,4,Z,9.9,7.4,8.8,202
1,AUDI,COMPACT,2.0,4,Z,11.5,8.1,10.0,230
2,AUDI,COMPACT,2.0,4,Z,10.8,7.5,9.3,214
3,AUDI,SUBCOMPACT,2.0,4,Z,11.5,8.1,10.0,230
4,AUDI,SUBCOMPACT,2.0,4,Z,11.5,8.1,10.0,230
...,...,...,...,...,...,...,...,...,...
2546,ROLLS-ROYCE,FULL-SIZE,6.6,12,Z,20.4,13.1,17.1,400
2547,ROLLS-ROYCE,FULL-SIZE,6.6,12,Z,20.4,13.1,17.1,400
2548,ROLLS-ROYCE,FULL-SIZE,6.7,12,Z,20.0,11.8,16.3,382
2549,ROLLS-ROYCE,FULL-SIZE,6.7,12,Z,20.0,11.8,16.3,382
2550,ROLLS-ROYCE,MID-SIZE,6.6,12,Z,19.6,12.8,16.5,387

In [28]:
print(df.info())   #빈 칼럼 여부 확인하기

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2551 entries, 0 to 2550
Data columns (total 9 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Make                              2551 non-null   object
 1   Vehicle Class                     2551 non-null   object
 2   Engine Size(L)                    2551 non-null   float64
 3   Cylinders                         2551 non-null   int64
 4   Fuel Type                         2551 non-null   object
 5   Fuel Consumption City (L/100 km)  2551 non-null   float64
 6   Fuel Consumption Hwy (L/100 km)   2551 non-null   float64
 7   Fuel Consumption Comb (L/100 km)  2551 non-null   float64
 8   CO2 Emissions(g/km)               2551 non-null   int64
dtypes: float64(4), int64(2), object(3)
memory usage: 179.5+ KB
None

In [29]:
from sklearn.preprocessing import LabelEncoder #문자 데이터를 수치값으로 변환하기(0~부터 시작 / Make, Vehicle Class, Fuel Type)
le = LabelEncoder()
df['Make'] = le.fit_transform(df['Make'])
df['Vehicle Class'] = le.fit_transform(df['Vehicle Class'])
df['Fuel Type'] = le.fit_transform(df['Fuel Type'])

In [31]:
df

,Make,Vehicle Class,Engine Size(L),Cylinders,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),CO2 Emissions(g/km)
0,0,0,2.0,4,4,9.9,7.4,8.8,202
1,0,0,2.0,4,4,11.5,8.1,10.0,230
2,0,0,2.0,4,4,10.8,7.5,9.3,214
3,0,10,2.0,4,4,11.5,8.1,10.0,230
4,0,10,2.0,4,4,11.5,8.1,10.0,230
...,...,...,...,...,...,...,...,...,...
2546,9,1,6.6,12,4,20.4,13.1,17.1,400
2547,9,1,6.6,12,4,20.4,13.1,17.1,400
2548,9,1,6.7,12,4,20.0,11.8,16.3,382
2549,9,1,6.7,12,4,20.0,11.8,16.3,382
2550,9,2,6.6,12,4,19.6,12.8,16.5,387

In [42]:
#정규화
df['Engine Size(L)'] = df['Engine Size(L)']/df['Engine Size(L)'].max()
df['Cylinders'] = df['Cylinders']/df['Cylinders'].max()
df['Fuel Consumption City (L/100 km)'] = df['Fuel Consumption City (L/100 km)']/df['Fuel Consumption City (L/100 km)'].max()
df['Fuel Consumption Hwy (L/100 km)'] = df['Fuel Consumption Hwy (L/100 km)']/df['Fuel Consumption Hwy (L/100 km)'].max()
df['Fuel Consumption Comb (L/100 km)'] = df['Fuel Consumption Comb (L/100 km)']/df['Fuel Consumption Comb (L/100 km)'].max()
df['CO2 Emissions(g/km)'] = df['CO2 Emissions(g/km)']/df['CO2 Emissions(g/km)'].max()

In [44]:
df   #전처리를 전부 끝낸 데이터프레임 출력

,Make,Vehicle Class,Engine Size(L),Cylinders,Fuel Type,Fuel Consumption City (L/100 km),Fuel Consumption Hwy (L/100 km),Fuel Consumption Comb (L/100 km),CO2 Emissions(g/km)
0,0,0,0.2500,0.25,4,0.323529,0.359223,0.337165,0.386973
1,0,0,0.2500,0.25,4,0.375817,0.393204,0.383142,0.440613
2,0,0,0.2500,0.25,4,0.352941,0.364078,0.356322,0.409962
3,0,10,0.2500,0.25,4,0.375817,0.393204,0.383142,0.440613
4,0,10,0.2500,0.25,4,0.375817,0.393204,0.383142,0.440613
...,...,...,...,...,...,...,...,...,...
2546,9,1,0.8250,0.75,4,0.666667,0.635922,0.655172,0.766284
2547,9,1,0.8250,0.75,4,0.666667,0.635922,0.655172,0.766284
2548,9,1,0.8375,0.75,4,0.653595,0.572816,0.624521,0.731801
2549,9,1,0.8375,0.75,4,0.653595,0.572816,0.624521,0.731801
2550,9,2,0.8250,0.75,4,0.640523,0.621359,0.632184,0.741379